kind: pipeline
type: docker
name: recipe-book

steps:
- name: build
  image: "node:20.9.0-alpine3.18"
  environment:
    VITE_API_KEY:
      from_secret: VITE_API_KEY
  commands:
  - npm i -g pnpm
  - pnpm i
  - pnpm run build

- name: copyfiles
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: HOST
    port: 22
    key:
      from_secret: SSH_KEY
    source: build
    target: ~/apps/recipe_book
    username:
      from_secret: USER
  when:
    branch: 
    - main
    event: 
    - push

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: HOST
    port: 22
    key:
      from_secret: SSH_KEY
    username:
      from_secret: USER
    script: bash ~/apps/recipe_book/deploy.sh
  when:
    branch:
    - main
    event:
    - push